FROM arm32v7/python:3.7-alpine
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
COPY openwrt_network_restarter.py openwrt_network_restarter.py

CMD python openwrt_network_restarter.py
